name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup cmake
      run: sudo apt install cmake

    - name: build
      run: |
        cmake -S . -B build
        cmake --build build
      
    - name: expect failures in run
      run: build/strong_tests
